name: mercur

services:

  postgres:
    image: postgres:17.5-alpine3.22
    container_name: pre-event-postgres
    restart: always
    environment:
      POSTGRES_USER: bravos
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: mercur
    networks:
      - pre-event-networks
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

networks:
  pre-event-networks:
    driver: bridge
